version: '3.8'

services:
  # 主应用服务
  app:
    image: ghcr.io/your-username/sillytavern-card:latest
    container_name: sillytavern-card
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # 挂载数据目录，确保数据持久化
      - ./data:/app/data
      - ./public:/app/public
    environment:
      - NODE_ENV=production
      - PORT=3000

volumes:
  # 数据持久化卷
  app-data:
    driver: local
